name: ci
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  # TODO: The new consumer group does not work with kafka 3.9, so I'm disabling CI for it for now
  # later we must skip some tests based on the supported features
  #
  # tests-v3_9:
  #   name: test-3.9
  #   runs-on: ubuntu-latest
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       include:
  #         - elixir: 1.17
  #           otp: 27
  #         - elixir: 1.16
  #           otp: 26
  #         - elixir: 1.15
  #           otp: 25
  #         - elixir: 1.14
  #           otp: 24
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: erlef/setup-beam@v1
  #       with:
  #         elixir-version: ${{ matrix.elixir }}
  #         otp-version: ${{ matrix.otp }}
  #     - run: docker compose -f "test/compose_files/docker-compose-kafka-3.9.yml" up -d
  #     - run: MIX_ENV=prod mix deps.get
  #     - run: MIX_ENV=prod mix compile --warnings-as-errors
  #     - run: KLIFE_KAFKA_VSN=3.9 mix test --warnings-as-errors

  tests-v4_0:
    name: test-4.0
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - elixir: 1.17
            otp: 27
          - elixir: 1.16
            otp: 26
          - elixir: 1.15
            otp: 25
          - elixir: 1.14
            otp: 24
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}
      - run: docker compose -f "test/compose_files/docker-compose-kafka-4.0.yml" up -d
      - run: MIX_ENV=prod mix deps.get
      - run: MIX_ENV=prod mix compile --warnings-as-errors
      - run: KLIFE_KAFKA_VSN=4.0 mix test --warnings-as-errors
